 version: '2'
 services:
   reporting:
     image: registry.manadrdev.com/attendances-reporting
     depends_on:
       - mongo
   mongo:
      image: mongo
#      volumes:
#        - /datadrive/attendances/d1:/var/lib/mongodb
#        - /datadrive/attendances/d2:/data/db
